In [304]:
import numpy as np
import copy


class LSystemBoardGen:
    def __init__(self, size, agent_count) -> None:
        self.size = size
        self.agent_count = agent_count
        self.board = self.initialise_starting_board(self.size, self.agent_count)
        self.agents = self.assign_agent_states()
        self.og_board = copy.deepcopy(self.board)
        self.og_agents = copy.deepcopy(self.agents)

    def initialise_starting_board(self, size:int, agent_count):
        """Initialise as starting board of shape (size, size) with agent_count agents."""
        # :TO UPDATE
        board = np.zeros(shape=(size,size), dtype=int)
        for agent in range(1, 1+agent_count):
            tries = 0
            while(1):
                tries += 1
                if tries == 100:
                    print(f'ERROR - NO BOARD SPACES FOUND AFTER {100} TRIES')
                    break

                idx0 = np.random.randint(0, self.size)
                idx1 = np.random.randint(0, self.size)
                if board[idx0, idx1] != 0.0:
                    continue
                else:
                    board[idx0, idx1] = agent
                    break
        return board

    def reset(self):
        """Reset board back to its original state."""
        self.board = self.og_board
        self.agents = self.og_agents

    def assign_agent_states(self):
        """Construct agent from board info. 
        
        Each agent has the following attributes:
        (agent_num, head, tail, head_history, tail_history)
        """
        agents = []
        for agent in range(1, 1+self.agent_count):
            pos = np.argwhere(self.board==agent)[0]
            agents.append([agent, pos, pos, [pos], [pos]])
        return agents

    def find_next_pos(self, loc:np.ndarray):
        """Find the next empty spot for an agent head/tail."""
        empty_places = np.argwhere(self.board==0)
        empty_place_distances = np.sqrt(np.sum((loc-empty_places)**2, axis=1))
        empty_neighbour_places = np.argwhere(empty_place_distances<1+1/9)
        empty_neighbour_coords = np.take(empty_places, empty_neighbour_places, axis=0)
        return empty_neighbour_coords[:,0,:]

    def push(self, agent_num):
        agent = self.agents[agent_num-1]
        growth_choice = np.random.randint(1, 3) # choose to grow from the head or the tail, :TO UPDATE
        nbs = self.find_next_pos(agent[growth_choice])
        
        try: # this can be ammended - at the moment a random growth direction is chosen
            growth_direction = np.random.randint(0, len(nbs))
        except:
            return -1
        
        self.board[tuple(nbs[growth_direction])] = agent[0]
        if not np.array_equal(agent[growth_choice+2][-1], agent[growth_choice]):            
            print('agent_growth_choice: ', agent[growth_choice])
            agent[growth_choice+2].append(agent[growth_choice])
        agent[growth_choice] = nbs[growth_direction]
        return None

    def pull(self, agent_num):
        agent = self.agents[agent_num-1]
        shrink_choice = np.random.randint(1, 3) #:TO UPDATE

        if len(agent[shrink_choice+2]) == 1:
            self.board[tuple(agent[shrink_choice])] = 0
            agent[shrink_choice] = agent[shrink_choice+2]
        else:
            self.board[tuple(agent[shrink_choice])] = 0
            loc = agent[shrink_choice+2].pop()
            print('loc', loc)
            agent[shrink_choice] = loc
        return None


In [306]:
Board = LSystemBoardGen(5, 3)
print(Board.board)



Board.push(3)
print(Board.agents[2])
print(Board.board)

Board.push(3)
print(Board.agents[2])
print(Board.board)

Board.push(3)
print(Board.agents[2])
print(Board.board)

Board.pull(3)
print(Board.agents[2])
print(Board.board)

Board.pull(3)
print(Board.agents[2])
print(Board.board)

Board.push(3)
print(Board.agents[2])
print(Board.board)

Board.pull(3)
print(Board.agents[2])
print(Board.board)

Board.pull(3)
print(Board.agents[2])
print(Board.board)


Board.push(3)
print(Board.agents[2])
print(Board.board)

Board.push(3)
print(Board.agents[2])
print(Board.board)

Board.push(3)
print(Board.agents[2])
print(Board.board)

Board.pull(3)
print(Board.agents[2])
print(Board.board)

Board.pull(3)
print(Board.agents[2])
print(Board.board)

Board.push(3)
print(Board.agents[2])
print(Board.board)

Board.pull(3)
print(Board.agents[2])
print(Board.board)

Board.pull(3)
print(Board.agents[2])
print(Board.board)


Board.push(3)
print(Board.agents[2])
print(Board.board)

Board.push(3)
print(Board.agents[2])
print(Board.board)

Board.push(3)
print(Board.agents[2])
print(Board.board)

Board.pull(3)
print(Board.agents[2])
print(Board.board)

Board.pull(3)
print(Board.agents[2])
print(Board.board)

Board.push(3)
print(Board.agents[2])
print(Board.board)

Board.pull(3)
print(Board.agents[2])
print(Board.board)

Board.pull(3)
print(Board.agents[2])
print(Board.board)

[[0 2 0 0 0]
 [0 0 0 3 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 1]]
[3, array([1, 3]), array([2, 3]), [array([1, 3])], [array([1, 3])]]
[[0 2 0 0 0]
 [0 0 0 3 0]
 [0 0 0 3 0]
 [0 0 0 0 0]
 [0 0 0 0 1]]
[3, array([0, 3]), array([2, 3]), [array([1, 3])], [array([1, 3])]]
[[0 2 0 3 0]
 [0 0 0 3 0]
 [0 0 0 3 0]
 [0 0 0 0 0]
 [0 0 0 0 1]]
agent_growth_choice:  [0 3]
[3, array([0, 4]), array([2, 3]), [array([1, 3]), array([0, 3])], [array([1, 3])]]
[[0 2 0 3 3]
 [0 0 0 3 0]
 [0 0 0 3 0]
 [0 0 0 0 0]
 [0 0 0 0 1]]
loc [0 3]
[3, array([0, 3]), array([2, 3]), [array([1, 3])], [array([1, 3])]]
[[0 2 0 3 0]
 [0 0 0 3 0]
 [0 0 0 3 0]
 [0 0 0 0 0]
 [0 0 0 0 1]]
[3, array([0, 3]), [array([1, 3])], [array([1, 3])], [array([1, 3])]]
[[0 2 0 3 0]
 [0 0 0 3 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 1]]
agent_growth_choice:  [0 3]
[3, array([0, 4]), [array([1, 3])], [array([1, 3]), array([0, 3])], [array([1, 3])]]
[[0 2 0 3 3]
 [0 0 0 3 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 1]]
loc [0 3]
[3, array([0, 3]), [